# Generated by Django 4.2.28 on 2026-02-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
